"""add date and time column

Revision ID: 3dd5b9a80a7f
Revises: 07aed618d77a
Create Date: 2025-08-25 15:39:36.863991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dd5b9a80a7f'
down_revision: Union[str, None] = '07aed618d77a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('article', sa.Column('time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'time')
    op.drop_column('article', 'date')
    # ### end Alembic commands ###
